package com.rochak.payflow.configs;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.rochak.payflow.dto.ChangePasswordDto;
import com.rochak.payflow.dto.SessionAuditReport;
import com.rochak.payflow.dto.SessionSecurityReport;
import com.rochak.payflow.dto.auth.AuthResponseDTO;
import com.rochak.payflow.dto.auth.LoginRequestDTO;
import com.rochak.payflow.dto.payment.CreatePaymentRequestDTO;
import com.rochak.payflow.dto.payment.CreatePaymentResponseDTO;
import com.rochak.payflow.dto.razorpay.RazorpayOrderRequest;
import com.rochak.payflow.dto.razorpay.RazorpayOrderResponse;
import com.rochak.payflow.dto.request.*;
import com.rochak.payflow.dto.response.TransactionResponseDTO;
import com.rochak.payflow.dto.response.UserResponseDTO;
import com.rochak.payflow.dto.response.WalletResponseDTO;
import com.rochak.payflow.entity.*;
import io.swagger.v3.core.converter.AnnotatedType;
import io.swagger.v3.core.converter.ModelConverters;
import io.swagger.v3.core.jackson.ModelResolver;
import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeType;
import io.swagger.v3.oas.annotations.info.Contact;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.info.License;
import io.swagger.v3.oas.annotations.security.SecurityScheme;
import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.tags.Tag;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;
import java.util.Map;

@Configuration
@OpenAPIDefinition(
        info = @Info(
                title = "PayFlow API",
                version = "1.0.0",
                description = """
                        PayFlow is a payment orchestration backend that manages authentication, Redis-backed sessions, wallets, transactions and Razorpay test-mode payments.

                        ## Documentation usage
                        This Swagger UI is documentation-only. API execution is intentionally disabled here. Use the project's Postman collection for API testing.

                        Protected endpoints require a JWT access token in the `Authorization: Bearer <access-token>` header. The token is obtained from `POST /api/auth/login`.

                        ## Main payment happy flow
                        1. Authenticate with PayFlow.
                        2. Create a PayFlow payment/order using `POST /api/payments/create-order`.
                        3. PayFlow creates the Razorpay order and returns the order information needed by the browser.
                        4. The frontend opens Razorpay Checkout in test mode.
                        5. Enter Razorpay test card details and the test OTP.
                        6. Razorpay returns the order ID, payment ID and signature to the frontend.
                        7. The frontend sends those values to `POST /api/payments/verify`.
                        8. PayFlow verifies the Razorpay signature and credits the user's wallet.

                        ## Internal architecture
                        Controllers expose HTTP contracts; services contain business logic; repositories persist data; mappers convert entities to API response DTOs. PostgreSQL stores persistent business data, Redis stores session state, and the Razorpay client handles payment-provider communication. Session audit/security reports are generated by scheduled jobs rather than REST endpoints.

                        ## Runtime note
                        The application should run with JVM parameter `-Duser.timezone=Asia/Kolkata` for compatibility with the PostgreSQL environment used by this project.
                        """,
                contact = @Contact(name = "PayFlow"),
                license = @License(name = "Project documentation")
        )
)
@SecurityScheme(
        name = "bearerAuth",
        type = SecuritySchemeType.HTTP,
        scheme = "bearer",
        bearerFormat = "JWT",
        description = "JWT access token. Obtain it from POST /api/auth/login. Swagger UI does not execute requests; use Postman for API testing."
)
public class OpenApiConfig {

//        static {
//                com.fasterxml.jackson.datatype.jsr310.JavaTimeModule javaTimeModule =
//                        new com.fasterxml.jackson.datatype.jsr310.JavaTimeModule();
//
//                io.swagger.v3.core.util.Json.mapper().registerModule(javaTimeModule);
//                io.swagger.v3.core.util.Yaml.mapper().registerModule(javaTimeModule);
//                io.swagger.v3.core.util.Json31.mapper().registerModule(javaTimeModule);
//                io.swagger.v3.core.util.Yaml31.mapper().registerModule(javaTimeModule);
//        }
//
//        @Bean
//        public ModelResolver modelResolver() {
//                ObjectMapper mapper = new ObjectMapper();
//                mapper.registerModule(new JavaTimeModule());
//                return new ModelResolver(mapper);
//        }

        @Bean
        public OpenAPI payflowOpenAPI() {
                OpenAPI openAPI = new OpenAPI()
                        .components(new Components())
                        .tags(List.of(
                                new Tag().name("Authentication").description("Login, refresh-token and logout operations."),
                                new Tag().name("Users").description("Public registration and authenticated self-service profile/password operations."),
                                new Tag().name("Wallet").description("Authenticated wallet operations for the current user."),
                                new Tag().name("Transactions").description("Authenticated transaction-history operations."),
                                new Tag().name("Payments").description("PayFlow payment-order creation and Razorpay payment verification."),
                                new Tag().name("Admin - Users").description("ADMIN-only user administration and administrator provisioning."),
                                new Tag().name("Admin - Wallets").description("ADMIN-only wallet inspection and freeze/unfreeze operations."),
                                new Tag().name("Admin - Transactions").description("ADMIN-only transaction inspection."),
                                new Tag().name("Actuator").description("Operational health, application information and metrics endpoints.")
                        ));

                // Add public API DTOs and internal developer-reference models to the Models section.
//                List<Class<?>> modelTypes = List.of(
//                        AuthResponseDTO.class, LoginRequestDTO.class,
//                        CreateUserRequestDTO.class, UserRequestDTO.class, ChangePasswordDto.class,
//                        LogoutRequestDto.class, RefreshTokenRequestDto.class,
//                        CreatePaymentRequestDTO.class, CreatePaymentResponseDTO.class, PaymentVerificationRequestDTO.class,
//                        TransferRequestDTO.class, WithdrawRequestDto.class, AddMoneyRequestDTO.class,
//                        UserResponseDTO.class, WalletResponseDTO.class, TransactionResponseDTO.class,
//                        RazorpayOrderRequest.class, RazorpayOrderResponse.class,
//                        SessionAuditReport.class, SessionSecurityReport.class,
//                        User.class, Wallet.class, Payment.class, Transaction.class, RefreshToken.class,
//                        Role.class, PaymentStatus.class, PaymentFailureReason.class,
//                        TransactionStatus.class, TransactionType.class, TransactionCategory.class
//                );

                List<Class<?>> dtoModels = List.of(
                        AuthResponseDTO.class,
                        LoginRequestDTO.class,
                        CreateUserRequestDTO.class,
                        UserRequestDTO.class,
                        ChangePasswordDto.class,
                        LogoutRequestDto.class,
                        RefreshTokenRequestDto.class,

                        CreatePaymentRequestDTO.class,
                        CreatePaymentResponseDTO.class,
                        PaymentVerificationRequestDTO.class,

                        TransferRequestDTO.class,
                        WithdrawRequestDto.class,

                        UserResponseDTO.class,
                        WalletResponseDTO.class,
                        TransactionResponseDTO.class
                );

                List<Class<?>> providerModels = List.of(
                        RazorpayOrderRequest.class,
                        RazorpayOrderResponse.class
                );

                List<Class<?>> entityModels = List.of(
                        User.class,
                        Wallet.class,
                        Payment.class,
                        Transaction.class,
                        RefreshToken.class
                );

                List<Class<?>> reportModels = List.of(
                        SessionAuditReport.class,
                        SessionSecurityReport.class
                );

                List<Class<?>> enumModels = List.of(
                        Role.class,
                        PaymentStatus.class,
                        PaymentFailureReason.class,
                        TransactionStatus.class,
                        TransactionType.class,
                        TransactionCategory.class
                );

//                List<Class<?>> modelTypes = new ArrayList<>();
//
//                modelTypes.addAll(dtoModels);
//                modelTypes.addAll(providerModels);
//                modelTypes.addAll(entityModels);
//                modelTypes.addAll(reportModels);
//                modelTypes.addAll(enumModels);

                registerSchemas(openAPI, dtoModels);
                registerSchemas(openAPI, providerModels);
                registerSchemas(openAPI, entityModels);
                registerSchemas(openAPI, reportModels);
                registerSchemas(openAPI, enumModels);

                return openAPI;
        }

        private void registerSchemas(
                OpenAPI openAPI,
                List<Class<?>> modelTypes
        ) {
                Components components = openAPI.getComponents();

                for (Class<?> modelType : modelTypes) {
                        try {
                                Map<String, Schema> schemas = ModelConverters.getInstance()
                                        .readAll(new AnnotatedType(modelType).resolveAsRef(false));
                                if (schemas.isEmpty()) {
                                        System.out.println("EMPTY schema for: " + modelType.getSimpleName());
                                }
                                schemas.forEach(components::addSchemas);
                        } catch (Exception e) {
                                System.out.println("FAILED for " + modelType.getSimpleName() + ": " + e);
                        }
                }
        }
}
