--
-- PostgreSQL database dump
--

\restrict c1pm6NGZUFsE8kC27x57kA3TIZAY45Wr2cJEZoNfoJ7VzPFcxxR6DMs9iQCzKcm

-- Dumped from database version 15.17 (Debian 15.17-1.pgdg13+1)
-- Dumped by pg_dump version 15.17 (Debian 15.17-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.payments DROP CONSTRAINT IF EXISTS fkj94hgy9v5fw1munb90tar2eje;
ALTER TABLE IF EXISTS ONLY public.transactions DROP CONSTRAINT IF EXISTS fke0ppnh35227iut4l5u6bgghyw;
ALTER TABLE IF EXISTS ONLY public.wallets DROP CONSTRAINT IF EXISTS fkc1foyisidw7wqqrkamafuwn4e;
ALTER TABLE IF EXISTS ONLY public.transactions DROP CONSTRAINT IF EXISTS fk5tr9f7tf144wrpoomtqyguilu;
ALTER TABLE IF EXISTS ONLY public.refresh_tokens DROP CONSTRAINT IF EXISTS fk1lih5y2npsf8u5o3vhdb9y0os;
ALTER TABLE IF EXISTS ONLY public.wallets DROP CONSTRAINT IF EXISTS wallets_pkey;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.wallets DROP CONSTRAINT IF EXISTS uksswfdl9fq40xlkove1y5kc7kv;
ALTER TABLE IF EXISTS ONLY public.refresh_tokens DROP CONSTRAINT IF EXISTS ukghpmfn23vmxfu3spu3lfg4r2d;
ALTER TABLE IF EXISTS ONLY public.payments DROP CONSTRAINT IF EXISTS ukc3w49re3w3eiexjdnm9khcsd8;
ALTER TABLE IF EXISTS ONLY public.payments DROP CONSTRAINT IF EXISTS uk_payments_receipt_id;
ALTER TABLE IF EXISTS ONLY public.refresh_tokens DROP CONSTRAINT IF EXISTS uk7tdcd6ab5wsgoudnvj7xf1b7l;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS uk3g1j96g94xpk3lpxl2qbl985x;
ALTER TABLE IF EXISTS ONLY public.transactions DROP CONSTRAINT IF EXISTS transactions_pkey;
ALTER TABLE IF EXISTS ONLY public.refresh_tokens DROP CONSTRAINT IF EXISTS refresh_tokens_pkey;
ALTER TABLE IF EXISTS ONLY public.payments DROP CONSTRAINT IF EXISTS payments_pkey;
DROP TABLE IF EXISTS public.wallets;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.transactions;
DROP TABLE IF EXISTS public.refresh_tokens;
DROP TABLE IF EXISTS public.payments;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount double precision NOT NULL,
    created_at timestamp(6) without time zone,
    razorpay_order_id character varying(255) NOT NULL,
    razorpay_payment_id character varying(255),
    status character varying(255) NOT NULL,
    user_id bigint,
    failure_reason character varying(255),
    verified_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    receipt_id character varying(255) NOT NULL,
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    revoked boolean NOT NULL,
    token text NOT NULL,
    user_id bigint
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    amount double precision NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    transaction_type character varying(255) NOT NULL,
    receiver_wallet_id bigint,
    sender_wallet_id bigint,
    category character varying(255),
    description character varying(255),
    external_reference character varying(100),
    CONSTRAINT transactions_category_check CHECK (((category)::text = ANY ((ARRAY['CREDIT'::character varying, 'DEBIT'::character varying, 'TRANSFER'::character varying])::text[])))
);


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallets (
    id bigint NOT NULL,
    balance double precision NOT NULL,
    user_id bigint NOT NULL,
    frozen boolean DEFAULT false
);


--
-- Name: wallets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.payments (id, amount, created_at, razorpay_order_id, razorpay_payment_id, status, user_id, failure_reason, verified_at, updated_at, receipt_id) FROM stdin;
1	500	2026-06-15 18:18:53.781626	order_T20H6XHSd7aFaZ	\N	PENDING	3	\N	\N	\N	LEGACY_1
2	100	2026-08-08 19:22:55.63248	order_TNOCyOpS3kchhb	\N	PENDING	2	NONE	\N	2026-08-08 19:22:55.63248	PAY_2dd342a2-5a52-4003-abe0-e2711b931236
3	100	2026-08-08 19:27:10.627741	order_TNOHSkPT6Nr6TR	\N	PENDING	2	NONE	\N	2026-08-08 19:27:10.627741	PAY_90364b58-c444-4199-87c2-b6273c46b3c3
4	100	2026-08-08 19:54:25.772251	order_TNOkFWqjPoQ62P	pay_TNOmcjmRfxh0XQ	SUCCESS	2	NONE	2026-08-08 19:58:38.156874	2026-08-08 19:58:38.156874	PAY_87fa6e33-74b9-4e7c-a140-5031ce4ddbe1
5	100	2026-08-10 17:44:30.578459	order_TO9bJgWrZga61g	pay_TO9cKa1z9WszgJ	SUCCESS	2	NONE	2026-08-10 17:45:51.137878	2026-08-10 17:45:51.137878	PAY_f22732f5-4794-4cb2-bfe2-c47ca7789f51
6	100	2026-08-10 19:04:22.696573	order_TOAxgLfTmLVPZp	pay_TOAyMI1jAUbtaa	SUCCESS	3	NONE	2026-08-10 19:05:18.419436	2026-08-10 19:05:18.419436	PAY_085e5df8-5f3d-44d6-a59f-98d75540a961
7	100	2026-08-17 20:30:24.60984	order_TQyABoOe13BtMn	pay_TQyBCEshvlM7cW	SUCCESS	3	NONE	2026-08-17 20:31:40.756243	2026-08-17 20:31:40.756243	PAY_217183bc-48c6-4aab-b8bf-073c030c5fbc
8	100	2026-08-21 19:41:25.240236	order_TSXSqufuM4G3Yw	pay_TSXUUches3wUM3	SUCCESS	3	NONE	2026-08-21 19:43:15.765129	2026-08-21 19:43:15.765129	PAY_81e7fcd4-1a10-4b86-9681-48ca23b342fc
9	100	2026-08-25 19:00:39.646273	order_TU6uKhMqAjUor5	pay_TU6v9ZcpTr0qDr	SUCCESS	3	NONE	2026-08-25 19:01:48.783048	2026-08-25 19:01:48.783058	PAY_0458716a-2988-465e-9bd9-cab41f7a2160
\.


--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.refresh_tokens (id, expiry_date, revoked, token, user_id) FROM stdin;
6	2026-06-29 18:19:33.964493	f	eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTc4MjE1MjM3MywiZXhwIjoxNzgyNzU3MTczfQ.o1mjRUcKYtsny1JQrvXLBD_tRtZnIKpaJZqjlVnY7mQrxKluEcGWFD8oS80jDKN5yBd0Zmox0qXn7JTcolrcKQ	1
20	2026-07-29 18:19:24.469434	f	eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbGxpZXdpbGxhbXNAZ21haWwuY29tIiwianRpIjoiOTFlYzEyYzgtZjQ5My00ODFhLWE0ZTYtMjJlZmU2NDdiYzliIiwic2lkIjoiZTMxZmFhYzktZTJlNy00NmY5LThjOGUtOWMxZTY3ZWViZWRlIiwiaWF0IjoxNzg0NzQ0MzY0LCJleHAiOjE3ODUzNDkxNjR9.sodvCayMYrXPn2M8AiTC8aW6aM2miNn9CvHFnjtVlXCDapViM51bEYB4Ih2hOusEH_UVT9fZIVRP8U7NmE_ErQ	2
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.transactions (id, amount, created_at, status, transaction_type, receiver_wallet_id, sender_wallet_id, category, description, external_reference) FROM stdin;
1	300	2026-05-12 19:33:49.773978	SUCCESS	TRANSFER	1	2	\N	\N	\N
2	300	2026-05-14 18:35:16.271077	SUCCESS	TRANSFER	2	1	\N	\N	\N
3	300	2026-05-20 19:38:03.459714	SUCCESS	TRANSFER	1	2	\N	\N	\N
4	300	2026-06-17 17:48:13.609652	SUCCESS	TRANSFER	2	1	\N	\N	\N
5	300	2026-06-18 18:08:25.574208	SUCCESS	TRANSFER	2	1	TRANSFER	Transfer from johndoe@gmail.com to elliewillams@gmail.com	\N
6	500	2026-06-22 18:25:45.93948	SUCCESS	WITHDRAWAL	\N	2	DEBIT	Wallet withdrawal	\N
7	300	2026-07-10 17:49:50.260992	SUCCESS	TRANSFER	1	2	TRANSFER	Transfer from elliewillams@gmail.com to johndoe@gmail.com	\N
8	1000	2026-07-10 17:55:32.441241	SUCCESS	DEPOSIT	2	\N	CREDIT	Adding money to wallet	\N
9	10	2026-07-10 17:57:23.735529	SUCCESS	DEPOSIT	2	\N	CREDIT	Adding money to wallet	\N
10	10	2026-07-15 19:59:52.186353	SUCCESS	DEPOSIT	2	\N	CREDIT	Adding money to wallet	\N
11	50000	2026-07-15 20:00:01.95304	SUCCESS	DEPOSIT	2	\N	CREDIT	Adding money to wallet	\N
12	10000	2026-07-15 20:00:54.143227	SUCCESS	TRANSFER	1	2	TRANSFER	Transfer from elliewillams@gmail.com to johndoe@gmail.com	\N
13	12000	2026-07-15 20:01:02.573533	SUCCESS	TRANSFER	1	2	TRANSFER	Transfer from elliewillams@gmail.com to johndoe@gmail.com	\N
14	10	2026-07-30 20:25:39.048998	SUCCESS	TRANSFER	1	2	TRANSFER	Transfer from elliewillams@gmail.com to johndoe@gmail.com	\N
15	100	2026-08-08 19:58:38.147079	SUCCESS	DEPOSIT	2	\N	CREDIT	Razorpay Wallet top-up	pay_TNOmcjmRfxh0XQ
16	100	2026-08-10 17:45:51.127339	SUCCESS	DEPOSIT	2	\N	CREDIT	Razorpay Wallet top-up	pay_TO9cKa1z9WszgJ
17	100	2026-08-10 19:05:18.407948	SUCCESS	DEPOSIT	3	\N	CREDIT	Razorpay Wallet top-up	pay_TOAyMI1jAUbtaa
18	100	2026-08-17 20:31:40.742864	SUCCESS	DEPOSIT	3	\N	CREDIT	Razorpay Wallet top-up	pay_TQyBCEshvlM7cW
19	10	2026-08-17 20:32:34.252815	SUCCESS	TRANSFER	1	2	TRANSFER	Transfer from elliewillams@gmail.com to johndoe@gmail.com	\N
20	100	2026-08-21 19:43:15.747912	SUCCESS	DEPOSIT	3	\N	CREDIT	Razorpay Wallet top-up	pay_TSXUUches3wUM3
21	10	2026-08-21 19:43:57.087245	SUCCESS	TRANSFER	1	3	TRANSFER	Transfer from rochakshrivastav02@gmail.com to johndoe@gmail.com	\N
22	10	2026-08-21 19:44:08.568118	SUCCESS	WITHDRAWAL	\N	3	DEBIT	Wallet withdrawal	\N
23	100	2026-08-25 19:01:48.740192	SUCCESS	DEPOSIT	3	\N	CREDIT	Razorpay Wallet top-up	pay_TU6v9ZcpTr0qDr
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, email, name, password, role) FROM stdin;
1	johndoe@gmail.com	John Doe	$2a$10$xs9x0Lu5g3.C8AqGFA/nq.1grgV5LafuNW6jLi.BYvDQYSswjpxJK	USER
2	elliewillams@gmail.com	Ellie Willams	$2a$10$A9NUVjQGPgMM/vyCKBBTFuaXK1oxYO1jBOuZ64GVqGEuUHTWKMQqa	ADMIN
3	rochakshrivastav02@gmail.com	Rochak Shrivastav	$2a$10$3axT7yrdQgRiAh.CclBicOKo.WiHGLmenI5bT5/bUeb9DJmkkRlDS	ADMIN
4	newtestuser@payflow.com	Updated Test User	$2a$10$L1hAqFKpGFnDGjkQexUNz.85zptOyS7bOXgvfqUZZUkPnnDikZHba	USER
\.


--
-- Data for Name: wallets; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.wallets (id, balance, user_id, frozen) FROM stdin;
2	29200	2	f
4	0	4	f
1	22530	1	f
3	380	3	f
\.


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.payments_id_seq', 9, true);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.refresh_tokens_id_seq', 20, true);


--
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.transactions_id_seq', 23, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- Name: wallets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.wallets_id_seq', 4, true);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: users uk3g1j96g94xpk3lpxl2qbl985x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk3g1j96g94xpk3lpxl2qbl985x UNIQUE (name);


--
-- Name: refresh_tokens uk7tdcd6ab5wsgoudnvj7xf1b7l; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uk7tdcd6ab5wsgoudnvj7xf1b7l UNIQUE (user_id);


--
-- Name: payments uk_payments_receipt_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk_payments_receipt_id UNIQUE (receipt_id);


--
-- Name: payments ukc3w49re3w3eiexjdnm9khcsd8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT ukc3w49re3w3eiexjdnm9khcsd8 UNIQUE (razorpay_order_id);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: wallets uksswfdl9fq40xlkove1y5kc7kv; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT uksswfdl9fq40xlkove1y5kc7kv UNIQUE (user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: wallets wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: transactions fk5tr9f7tf144wrpoomtqyguilu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk5tr9f7tf144wrpoomtqyguilu FOREIGN KEY (receiver_wallet_id) REFERENCES public.wallets(id);


--
-- Name: wallets fkc1foyisidw7wqqrkamafuwn4e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT fkc1foyisidw7wqqrkamafuwn4e FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: transactions fke0ppnh35227iut4l5u6bgghyw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fke0ppnh35227iut4l5u6bgghyw FOREIGN KEY (sender_wallet_id) REFERENCES public.wallets(id);


--
-- Name: payments fkj94hgy9v5fw1munb90tar2eje; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkj94hgy9v5fw1munb90tar2eje FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict c1pm6NGZUFsE8kC27x57kA3TIZAY45Wr2cJEZoNfoJ7VzPFcxxR6DMs9iQCzKcm

