apiVersion: v1
kind: Pod
metadata:
  name: redis-migration
  namespace: payflow
spec:
  restartPolicy: Never
  containers:
    - name: migration
      image: redis/redis-stack-server:latest
      command:
        - sh
        - -c
        - "sleep 3600"
      volumeMounts:
        - name: redis-data
          mountPath: /data
  volumes:
    - name: redis-data
      persistentVolumeClaim:
        claimName: redis-pvc