spring.application.name=payflow

#postgresql setup
spring.datasource.url = jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword

#postgresql driver
spring.datasource.driver-class-name = org.postgresql.Driver

#jpa setup
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL (optional, good for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#security features
jwt.secret=payflowSecretKeyForJwtAuthenticationVerySecure123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
jwt.expiration=86400000
jwt.refresh-expiration=604800000

#razorpay details
razorpay.key.id=rzp_test_SuUQMBpgsib54Y
razorpay.key.secret=w5nki8T5Nds60JVDhkMaFLIY

#Actuator properties
management.endpoints.web.exposure.include=health,info,metrics,prometheus,startup
management.endpoint.health.show-details=when_authorized

# Application information
management.info.env.enabled=true
info.app.name=PayFlow
info.app.description=Payment Orchestration API
info.app.version=1.0.0

# OpenAPI / Swagger documentation
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Documentation only - do not allow API execution from Swagger UI
springdoc.swagger-ui.tryItOutEnabled=false
springdoc.swagger-ui.supportedSubmitMethods=

# Swagger organization
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.docExpansion=none

# Include Actuator endpoints in OpenAPI documentation
springdoc.show-actuator=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.connect-timeout=2s
spring.data.redis.timeout=2s

#hikari configuraiton HikariCP
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Initialize Spring MVC DispatcherServlet during application startup
spring.mvc.servlet.load-on-startup=1
spring.main.lazy-initialization=false


#docker run -d --name postgres-db -e POSTGRES_DB=mydb -e POSTGRES_USER=myuser -e POSTGRES_PASSWORD=mypassword -e TZ=Asia/Kolkata -p 5432:5432 postgres:15
#docker run -d --name redis-server -p 6379:6379 redis/redis-stack-server:latest
#docker exec -it postgres-db psql -U myuser -d mydb
#docker exec -it redis-server redis-cli
#docker compose down -v
#docker compose up -d