spring.application.name=payflow

#postgresql setup
spring.datasource.url = jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword

#postgresql driver
spring.datasource.driver-class-name = org.postgresql.Driver

#jpa setup
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL (optional, good for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#security features
jwt.secret=payflowSecretKeyForJwtAuthenticationVerySecure123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
jwt.expiration=86400000

#razorpay details
razorpay.key.id=rzp_test_SuUQMBpgsib54Y
razorpay.key.secret=w5nki8T5Nds60JVDhkMaFLIY
#docker run -d --name postgres-db -e POSTGRES_DB=mydb -e POSTGRES_USER=myuser -e POSTGRES_PASSWORD=mypassword -e TZ=Asia/Kolkata -p 5432:5432 postgres:15