apiVersion: v1
kind: Secret
metadata:
  name: payflow-secret
  namespace: payflow
type: Opaque
stringData:
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"

  JWT_SECRET: "payflowSecretKeyForJwtAuthenticationVerySecure123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

  RAZORPAY_KEY_ID: "rzp_test_SuUQMBpgsib54Y"
  RAZORPAY_KEY_SECRET: "w5nki8T5Nds60JVDhkMaFLIY"