apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payflow-logs-pvc
  namespace: payflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi